#!/usr/bin/env php
<?php
$argv = $_SERVER['argv'];
$argc = $_SERVER['argc'];
if ($argc < 2) {
    echo "Qadamchi CLI v2.2 – php qadamchi <command> [options]\n";
    exit;
}
$command = str_replace(':', '_', $argv[1]);
$cliFile = __DIR__ . '/app/Cli/' . $command . '.php';
if (!file_exists($cliFile)) {
    echo "Noto‘g‘ri buyruq: {$argv[1]}\n";
    exit(1);
}
require $cliFile;