<?php
namespace Qadamchi\Database\Grammars;

use Qadamchi\Database\Blueprint;
use Qadamchi\Database\ColumnDefinition;

/**
 * PostgreSQL grammar — SKELET (keyinroq to'ldiriladi).
 *
 * Hozircha asosiy DDL/inspectatsiya to'ldirilgan, lekin to'liq sinovdan o'tmagan.
 * Pg ishlatish uchun: .env'da DB_CONNECTION=pgsql. Yakuniy sozlash keyingi versiyada.
 */
class PostgresGrammar extends SchemaGrammar
{
    public function wrap(string $name): string
    {
        return '"' . str_replace('"', '""', $name) . '"';
    }

    protected function typeSql(ColumnDefinition $c): string
    {
        switch ($c->type) {
            case 'bigIncrements': return 'BIGSERIAL';          // GENERATED BY DEFAULT AS IDENTITY alternativasi
            case 'increments':    return 'SERIAL';
            case 'string':        return 'VARCHAR(' . (int) $c->params['length'] . ')';
            case 'text':
            case 'mediumText':
            case 'longText':      return 'TEXT';
            case 'integer':       return 'INTEGER';
            case 'bigInteger':    return 'BIGINT';
            case 'smallInteger':  return 'SMALLINT';
            case 'boolean':       return 'BOOLEAN';
            case 'float':         return 'DOUBLE PRECISION';
            case 'decimal':       return 'DECIMAL(' . (int) $c->params['precision'] . ',' . (int) $c->params['scale'] . ')';
            case 'enum':          return 'TEXT'; // PostgreSQL'da alohida CREATE TYPE kerak — bu yerda CHECK bilan
            case 'json':          return 'JSONB';
            case 'date':          return 'DATE';
            case 'time':          return 'TIME';
            case 'datetime':      return 'TIMESTAMP';
            case 'timestamp':     return 'TIMESTAMP';
            case 'foreignId':     return 'BIGINT';
            default:              return 'VARCHAR(255)';
        }
    }

    protected function primaryKeyAppended(): bool { return true; } // SERIAL, lekin PK alohida

    public function compileColumn(ColumnDefinition $c): string
    {
        $sql = parent::compileColumn($c);
        if ($c->type === 'enum' && !empty($c->params['allowed'])) {
            $list = $this->quoteStringList($c->params['allowed']);
            $sql .= ' CHECK (' . $this->wrap($c->name) . ' IN (' . $list . '))';
        }
        return $sql;
    }

    public function createTableSuffix(): string { return ''; } // ENGINE/CHARSET yo'q

    public function compileIndexes(Blueprint $b): array
    {
        $after = [];
        $columns = $b->getColumns();
        foreach ($columns as $c) {
            if ($this->isIncrement($c)) continue;
            if ($c->unique) {
                $after[] = 'CREATE UNIQUE INDEX ' . $b->getTable() . '_' . $c->name . '_unique ON ' . $this->wrap($b->getTable()) . ' (' . $this->wrap($c->name) . ')';
            }
            if ($c->index) {
                $after[] = 'CREATE INDEX ' . $b->getTable() . '_' . $c->name . '_index ON ' . $this->wrap($b->getTable()) . ' (' . $this->wrap($c->name) . ')';
            }
        }
        return ['inline' => [], 'after' => $after];
    }

    public function alterAddColumnPrefix(): string { return 'ADD COLUMN'; }

    public function listTablesSql(): string
    {
        return "SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname = 'public' ORDER BY tablename";
    }

    public function hasTableSql(): string
    {
        return 'SELECT to_regclass(?)';
    }

    public function listColumnsSql(string $table): string
    {
        return "SELECT column_name AS Field, data_type AS Type FROM information_schema.columns WHERE table_name = '" . addslashes($table) . "'";
    }

    public function dropAllTables(array $tables): array
    {
        $stmts = ["SET session_replication_role = 'replica'"];
        foreach ($tables as $tbl) {
            $stmts[] = 'DROP TABLE IF EXISTS ' . $this->wrap($tbl) . ' CASCADE';
        }
        $stmts[] = "SET session_replication_role = 'origin'";
        return $stmts;
    }
}