name: CI

on:
  push:
    branches: [ main, version-2 ]
  pull_request:
    branches: [ main, version-2 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Run tests
      run: vendor/bin/phpunit tests/